version: "3.8"
services:
  web:
    image : chat-bot-service
    container_name: chatbotservice
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
